name: saml
description: Utility library for smal
version: 1.1.2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  uuid:
  xml: ^5.3.1
  rsa_pkcs:
  pointycastle:

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
