name: saml
description: Utility library for smal
version: 1.0.0

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
   xml:
   rsa_pkcs:
   pointycastle:

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
